title = "Configuration TOML"

[owner]
name = "Jemma Starecki"
git_link = "https://github.com/JemmaFromJupiter"

[client]
client_name = "Jupiter Edits"
client_version = "1.1.3"
client_dimensions = "1280x720"
client_hidden = [ "md", "gitignore", "pyc", "bat", "config", "replit", "nix", "upm", "lock", "cache", "breakpoints", "__pycache__", "toml",]

[user]
linewrap = "word"
theme = "newbie"
browsing_dir = "C:/Users/16282005/Desktop/TestingFeatures"

[theme]
[[theme.themes]]
NAME = "AnotherTheme"
BACKGROUND = "#400080"
TEXT = "#ffffff"
INPUT = "#8080ff"
TEXT_INPUT = "#000000"
SCROLL = "#25004a"
BUTTON = [ "#c488ff", "#e7ceff",]
PROGRESS = [ "#ad5bff", "#972fff",]
BORDER = "1"
SLIDER_DEPTH = "0"
PROGRESS_DEPTH = "0"

[[theme.themes]]
NAME = "Blues"
BACKGROUND = "#004080"
TEXT = "#ffffff"
INPUT = "#00ffff"
TEXT_INPUT = "#000000"
SCROLL = "#0000a0"
BUTTON = [ "#156a8a", "#2c5974",]
PROGRESS = [ "#007b9f", "#007b9f",]
BORDER = "1"
SLIDER_DEPTH = "0"
PROGRESS_DEPTH = "0"

[[theme.themes]]
NAME = "DireRed"
BACKGROUND = "#ff4242"
TEXT = "#494949"
INPUT = "#ff8083"
TEXT_INPUT = "#000000"
SCROLL = "#fe8034"
BUTTON = [ "#f9fc72", "#dd4242",]
PROGRESS = [ "#b46b6b", "#e03f3f",]
BORDER = "1"
SLIDER_DEPTH = "1"
PROGRESS_DEPTH = "1"

[[theme.themes]]
NAME = "newbie"
BACKGROUND = "#000000"
TEXT = "#ffffff"
INPUT = "#484848"
TEXT_INPUT = "#ffffff"
SCROLL = "#7e7e7e"
BUTTON = [ "#3f3f3f", "#8b8b8b",]
PROGRESS = [ "#444444", "#9e9e9e",]
BORDER = "2"
SLIDER_DEPTH = "1"
PROGRESS_DEPTH = "1"

[[theme.themes]]
NAME = "Obnoxious"
BACKGROUND = "#00ff80"
TEXT = "#004040"
INPUT = "#ff8040"
TEXT_INPUT = "#ff80ff"
SCROLL = "#808000"
BUTTON = [ "#b90746", "#ffff80",]
PROGRESS = [ "#870c78", "#00ff80",]
BORDER = "1"
SLIDER_DEPTH = "1"
PROGRESS_DEPTH = "1"

[client.fmts]
lin_dar = [ "linux", "darwin",]
win = [ "win32", "cygwin",]

[client.description]
desc = "Copyright JemmaFromJupiter on GitHub\n\nThis is a simple text editor that supports the creation\nof simple text files and more, You are able to run python programs,\nthat is the biggest limitation."
