title = "Configuration TOML"

[owner]
name = "Jemma Starecki"
git_link = "https://github.com/JemmaFromJupiter"

[client]
client_name = "Jupiter Edits"
client_version = "1.1.3"
client_dimensions = "1280x720"
client_hidden = [ "md", "gitignore", "pyc", "bat", "config", "replit", "nix", "upm", "lock", "cache", "breakpoints", "__pycache__", "toml",]

[user]
linewrap = "word"
theme = "DarkBlack"
browsing_dir = "current"

[client.fmts]
lin_dar = [ "linux", "darwin",]
win = [ "win32", "cygwin",]

[client.description]
desc = "Copyright JemmaFromJupiter on GitHub\n\nThis is a simple text editor that supports the creation\nof simple text files and more, You are able to run python programs,\nthat is the biggest limitation."
